### ISSUE TITLE
Postinstall script not working

### ISSUE THREAD

**Issue by ditorojuan** [mattpocock/sextant#12]
When running `yarn install` on a fresh repo clone, the `postinstall` script is failing. This makes sense as `packages/core` is trying to use `lib/index.js` as main entry AND  `lib/index.js` is only available once running `yarn build`.

## Stack Trace 
```
Scanning File: packages/frontend/src/components/keepDataInSync.machine.ts
Error: Cannot find module '/Users/juanditoro/open-source/sextant/node_modules/@sextant-tools/core/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/juanditoro/open-source/sextant/packages/frontend/src/components/keepDataInSync-machine-ts-j5gbi67cgzc.xstate.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.module_1.default._extensions..xstate.js (/Users/juanditoro/open-source/sextant/node_modules/xstate-codegen/bin/extractMachines.js:72:12)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/juanditoro/open-source/sextant/node_modules/@sextant-tools/core/package.json',
  requestPath: '@sextant-tools/core'
}
Could not complete due to errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sextant-monorepo@0.0.1 codegen:machines: `xstate-codegen "./!(node_modules)/!(node_modules)/**/**.machine.ts" --once`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sextant-monorepo@0.0.1 codegen:machines script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanditoro/.npm/_logs/2020-10-31T13_50_49_214Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

@mattpocock

**Comment by mattpocock** [comment]
@ditorojuan Gotcha, this is my bad. I've added a commit on master which fixes this.

**Comment by mattpocock** [comment]
@ditorojuan Can I close this? Assuming so from your ❤️
